const changeTheme = () => {
  const body = document.querySelector('body');
  const div = document.createElement('div');
  div.className = 'theme';
  body.append(div);
  const select = document.createElement('select');
  select.className = 'theme__option';
  div.append(select);
  const option = document.createElement('option');
  option.className = 'theme__option';
  option.innerText = 'Black theme';
  option.value = 'black';
  const option2 = document.createElement('option');
  option2.className = 'theme__option';
  option2.innerText = 'White theme';
  option2.value = 'white';
  select.append(option2);
  select.append(option);
};
changeTheme();
